accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url('signup/', views.signup, name='registration'),
    url(r'^activate/(?P<uid64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/info/<int:id>', views.ProfileInfoView.as_view(), name='info'),
    url('users/', views.UsersView.as_view(), name='users'),
]

meow_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', IndexView.as_view(), name='index'),
    path('summernote/', include('django_summernote.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('comment/', include('comment.urls')),
    path('api/', include('comment.api.urls')),
    path('', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostsView.as_view(), name='all'),
    path('single/<int:id>', views.single_post, name='single_post'),
    path('create', views.create_post, name='create_post'),
    path('edit/<int:id>', views.EditPostView.as_view(), name='edit_post'),
    path('delete/<int:id>', views.DeletePostView.as_view(), name='delete_post'),
    path('user', views.UserPostsView.as_view(), name='user_posts'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from crum import get_current_user
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment


class Posts(models.Model):
    name = models.CharField(max_length=255)
    post = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.CharField(max_length=255, default='')
    comments = GenericRelation(Comment)
    is_published = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        user = get_current_user()
        self.user = user
        super(Posts, self).save(*args, **kwargs)


class Tags(models.Model):
    tag = models.CharField(max_length=255)

posts/forms.py
from django import forms
from .models import Posts
from django.contrib.auth.models import User
from django_summernote.widgets import SummernoteWidget
from django.utils.translation import gettext_lazy as _


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')


class PostForm(forms.ModelForm):
    name = forms.CharField(label=_("post_title_field"),
                           required=True)
    # tags = forms.CharField(label=_("post_tags_field"),
    #                        required=False)
    post = forms.CharField(label=_("post_body_field"),
                           required=True, widget=SummernoteWidget({'width': '100%', 'height': '600px'}))

    is_published = forms.BooleanField(label=_("post_publish_field"), show_hidden_initial=False, required=False,
                                      widget=forms.CheckboxInput(
                                          attrs={'class': 'switch'}))

    class Meta:
        model = Posts
        fields = ('name', 'post', 'is_published')


class PostSearchForm(forms.Form):
    name = forms.CharField(
        label=_("post_title_field"),
        required=False,
        widget=forms.TextInput(attrs={'autocomplete': 'off'})
    )

posts/views.py
from django.shortcuts import render
from .models import Posts
from .forms import PostForm, PostSearchForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views import View
from django.utils.decorators import method_decorator
from django.shortcuts import get_object_or_404, redirect
from django.core.exceptions import PermissionDenied


class PostsView(View):
    template_name = 'pages/posts.html'
    search_form = PostSearchForm

    def get(self, request):
        name = request.GET.get('name', '')
        posts = Posts.objects.all().filter(name__contains=name, is_published=True).order_by('-pub_date')
        current_page = Paginator(posts, 10)
        page = request.GET.get('page')
        search_form = self.search_form(request.GET)
        try:
            posts_list = current_page.page(page)
        except PageNotAnInteger:
            posts_list = current_page.page(1)
        except EmptyPage:
            posts_list = current_page.page(current_page.num_pages)

        return render(request, self.template_name, {'page': page, 'page_obj': posts_list, 'form': search_form})


class UserPostsView(View):
    template_name = 'pages/user_posts.html'
    search_form = PostSearchForm

    @method_decorator(login_required)
    def get(self, request):
        print(request.user.id)
        posts = Posts.objects.all().filter(user=request.user.id).order_by('-pub_date')
        current_page = Paginator(posts, 10)
        page = request.GET.get('page')
        try:
            posts_list = current_page.page(page)
        except PageNotAnInteger:
            posts_list = current_page.page(1)
        except EmptyPage:
            posts_list = current_page.page(current_page.num_pages)

        return render(request, self.template_name, {'page': page, 'page_obj': posts_list})


def single_post(request, id):
    post = Posts.objects.get(pk=id)
    return render(request, 'pages/single_post.html', {'post': post})


@login_required
def create_post(request):
    if request.method == 'POST':
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            post_form.save()
            messages.info(request, 'Your post saved')
            return redirect('posts:user_posts')
    else:
        post_form = PostForm()
    return render(request, 'pages/create_post.html', {
        'form': post_form,
    })


class EditPostView(View):
    template_name = 'pages/edit_post.html'

    @method_decorator(login_required)
    def get(self, request, id):
        post = get_object_or_404(Posts, id=id)

        if request.user.id != post.user_id:
            raise PermissionDenied

        post_form = PostForm({'name': post.name, 'post': post.post, 'is_published': post.is_published})

        return render(request, self.template_name, {
            'form': post_form,
        })

    @method_decorator(login_required)
    def post(self, request, id):
        instance = get_object_or_404(Posts, id=id)
        if request.user.id != instance.user_id:
            raise PermissionDenied

        post_form = PostForm(request.POST, instance=instance)
        if post_form.is_valid():
            post_form.save()
            messages.info(request, 'Your post saved')
            return redirect('posts:single_post', instance.id)
        return render(request, self.template_name, {
            'form': post_form,
        })


class DeletePostView(View):

    def get(self, request, id):
        post_to_delete = Posts.objects.get(id=id)
        if request.user.id == post_to_delete.user_id:
            post_to_delete.delete()
            return redirect('posts:user_posts')
        return PermissionDenied()

templates/pages/chat.html
{% extends "../base.html" %}

{% block content %}
<div class="chat-container pr-4 pl-4">
  <!-- For demo purpose-->

  <div class="row rounded-lg overflow-hidden shadow">
    <!-- Users box-->
    <div class="d-flex flex-grow-1 col-3 px-0">
      <div class="bg-white">
        <div class="messages-box">
          <div class="list-group rounded-0">
            <a class="list-group-item list-group-item-action active text-white rounded-0">
              <div class="media"><img src="https://res.cloudinary.com/mhmd/image/upload/v1564960395/avatar_usae7z.svg" alt="user" width="50" class="rounded-circle">
                <div class="media-body ml-4">
                  <div class="d-flex align-items-center justify-content-between mb-1">
                    <h6 class="mb-0">Jason Doe</h6><small class="small font-weight-bold">25 Dec</small>
                  </div>
                  <p class="font-italic mb-0 text-small">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
                </div>
              </div>
            </a>

            <a href="#" class="list-group-item list-group-item-action list-group-item-light rounded-0">
              <div class="media"><img src="https://res.cloudinary.com/mhmd/image/upload/v1564960395/avatar_usae7z.svg" alt="user" width="50" class="rounded-circle">
                <div class="media-body ml-4">
                  <div class="d-flex align-items-center justify-content-between mb-1">
                    <h6 class="mb-0">Jason Doe</h6><small class="small font-weight-bold">14 Dec</small>
                  </div>
                  <p class="font-italic text-muted mb-0 text-small">Lorem ipsum dolor sit amet, consectetur. incididunt ut labore.</p>
                </div>
              </div>
            </a>

            <a href="#" class="list-group-item list-group-item-action list-group-item-light rounded-0">
              <div class="media"><img src="https://res.cloudinary.com/mhmd/image/upload/v1564960395/avatar_usae7z.svg" alt="user" width="50" class="rounded-circle">
                <div class="media-body ml-4">
                  <div class="d-flex align-items-center justify-content-between mb-1">
                    <h6 class="mb-0">Jason Doe</h6><small class="small font-weight-bold">9 Nov</small>
                  </div>
                  <p class="font-italic text-muted mb-0 text-small">consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
                </div>
              </div>
            </a>

            <a href="#" class="list-group-item list-group-item-action list-group-item-light rounded-0">
              <div class="media"><img src="https://res.cloudinary.com/mhmd/image/upload/v1564960395/avatar_usae7z.svg" alt="user" width="50" class="rounded-circle">
                <div class="media-body ml-4">
                  <div class="d-flex align-items-center justify-content-between mb-1">
                    <h6 class="mb-0">Jason Doe</h6><small class="small font-weight-bold">18 Oct</small>
                  </div>
                  <p class="font-italic text-muted mb-0 text-small">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
                </div>
              </div>
            </a>

            <a href="#" class="list-group-item list-group-item-action list-group-item-light rounded-0">
              <div class="media"><img src="https://res.cloudinary.com/mhmd/image/upload/v1564960395/avatar_usae7z.svg" alt="user" width="50" class="rounded-circle">
                <div class="media-body ml-4">
                  <div class="d-flex align-items-center justify-content-between mb-1">
                    <h6 class="mb-0">Jason Doe</h6><small class="small font-weight-bold">17 Oct</small>
                  </div>
                  <p class="font-italic text-muted mb-0 text-small">consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
                </div>
              </div>
            </a>

            <a href="#" class="list-group-item list-group-item-action list-group-item-light rounded-0">
              <div class="media"><img src="https://res.cloudinary.com/mhmd/image/upload/v1564960395/avatar_usae7z.svg" alt="user" width="50" class="rounded-circle">
                <div class="media-body ml-4">
                  <div class="d-flex align-items-center justify-content-between mb-1">
                    <h6 class="mb-0">Jason Doe</h6><small class="small font-weight-bold">2 Sep</small>
                  </div>
                  <p class="font-italic text-muted mb-0 text-small">Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                </div>
              </div>
            </a>

            <a href="#" class="list-group-item list-group-item-action list-group-item-light rounded-0">
              <div class="media"><img src="https://res.cloudinary.com/mhmd/image/upload/v1564960395/avatar_usae7z.svg" alt="user" width="50" class="rounded-circle">
                <div class="media-body ml-4">
                  <div class="d-flex align-items-center justify-content-between mb-1">
                    <h6 class="mb-0">Jason Doe</h6><small class="small font-weight-bold">30 Aug</small>
                  </div>
                  <p class="font-italic text-muted mb-0 text-small">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
                </div>
              </div>
            </a>

            <a href="#" class="list-group-item list-group-item-action list-group-item-light rounded-0">
              <div class="media"><img src="https://res.cloudinary.com/mhmd/image/upload/v1564960395/avatar_usae7z.svg" alt="user" width="50" class="rounded-circle">
                <div class="media-body ml-4">
                  <div class="d-flex align-items-center justify-content-between mb-3">
                    <h6 class="mb-0">Jason Doe</h6><small class="small font-weight-bold">21 Aug</small>
                  </div>
                  <p class="font-italic text-muted mb-0 text-small">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
                </div>
              </div>
            </a>

          </div>
        </div>
      </div>
    </div>
    <!-- Chat Box-->
    <div class="col px-0">
      <div class="px-4 py-5 bg-white chat-box">
        <!-- Sender Message-->
        <div class="media w-50 mb-3"><img src="https://res.cloudinary.com/mhmd/image/upload/v1564960395/avatar_usae7z.svg" alt="user" width="50" class="rounded-circle">
          <div class="media-body ml-3">
            <div class="bg-light rounded py-2 px-3 mb-2">
              <p class="text-small mb-0 text-muted">Test which is a new approach all solutions</p>
            </div>
            <p class="small text-muted">12:00 PM | Aug 13</p>
          </div>
        </div>

        <!-- Reciever Message-->
        <div class="media w-50 ml-auto mb-3">
          <div class="media-body">
            <div class="bg-primary rounded py-2 px-3 mb-2">
              <p class="text-small mb-0 text-white">Test which is a new approach to have all solutions</p>
            </div>
            <p class="small text-muted">12:00 PM | Aug 13</p>
          </div>
        </div>

        <!-- Sender Message-->
        <div class="media w-50 mb-3"><img src="https://res.cloudinary.com/mhmd/image/upload/v1564960395/avatar_usae7z.svg" alt="user" width="50" class="rounded-circle">
          <div class="media-body ml-3">
            <div class="bg-light rounded py-2 px-3 mb-2">
              <p class="text-small mb-0 text-muted">Test, which is a new approach to have</p>
            </div>
            <p class="small text-muted">12:00 PM | Aug 13</p>
          </div>
        </div>

        <!-- Reciever Message-->
        <div class="media w-50 ml-auto mb-3">
          <div class="media-body">
            <div class="bg-primary rounded py-2 px-3 mb-2">
              <p class="text-small mb-0 text-white">Apollo University, Delhi, India Test</p>
            </div>
            <p class="small text-muted">12:00 PM | Aug 13</p>
          </div>
        </div>

        <!-- Sender Message-->
        <div class="media w-50 mb-3"><img src="https://res.cloudinary.com/mhmd/image/upload/v1564960395/avatar_usae7z.svg" alt="user" width="50" class="rounded-circle">
          <div class="media-body ml-3">
            <div class="bg-light rounded py-2 px-3 mb-2">
              <p class="text-small mb-0 text-muted">Test, which is a new approach</p>
            </div>
            <p class="small text-muted">12:00 PM | Aug 13</p>
          </div>
        </div>

        <!-- Reciever Message-->
        <div class="media w-50 ml-auto mb-3">
          <div class="media-body">
            <div class="bg-primary rounded py-2 px-3 mb-2">
              <p class="text-small mb-0 text-white">Apollo University, Delhi, India Test</p>
            </div>
            <p class="small text-muted">12:00 PM | Aug 13</p>
          </div>
        </div>

      </div>

      <!-- Typing area -->
      <form action="#" class="bg-light" id="message-form">
        <div class="input-group">
          <input type="text" placeholder="Type a message" aria-describedby="button-addon2" class="form-control rounded-0 border-0 py-4 bg-light">
          <div class="input-group-append">
            <button id="button-addon2" type="submit" class="btn btn-link"> <i class="fa fa-paper-plane"></i></button>
          </div>
        </div>
      </form>

    </div>
  </div>
</div>
{% endblock %}
{% block footer %}{% endblock %}

templates/pages/create_post.html
{% extends "../base.html" %}

{% load crispy_forms_tags static i18n %}

{% block title %}{% trans 'create_post_title' %}{% endblock %}

{% block content %}
 <main role="main" class="flex-shrink-0">
     <div class="container">
        <form method="post" novalidate>
        <h1 class="h3 mb-3 font-weight-normal">{% trans 'create_post_title' %}</h1>
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ next }}">
          {{ form|crispy }}
        <button class="btn btn-primary" type="submit">{% trans 'create_post_submit_btn' %}</button>
        </form>
    </div>
 </main>
{% endblock %}

templates/pages/edit_post.html
{% extends "../base.html" %}

{% load crispy_forms_tags static i18n %}

{% block title %}{% trans 'edit_post_title' %}{% endblock %}

{% block content %}
 <main role="main" class="flex-shrink-0">
     <div class="container">
        <form method="post" novalidate>
        <h1 class="h3 mb-3 font-weight-normal">{% trans 'edit_post_title' %}</h1>
          {% csrf_token %}
          {{ form|crispy }}
        <button class="btn btn-primary" type="submit">{% trans 'edit_post_submit_btn' %}</button>
        </form>
    </div>
 </main>
{% endblock %}

templates/pages/index.html
{% extends "../base.html" %}
{% load static %}
{% block title %}My amazing blog{% endblock %}
{% block content %}
<section id="index-bg">
    <span class="display-1">千里之行，始于足下</span>
</section>
{% endblock %}
{% block footer %}{% endblock %}

templates/pages/posts.html
{% extends "../base.html" %}
{% block title %}My amazing blog{% endblock %}
{% load crispy_forms_tags i18n static %}
{% block content %}
<main role="main" class="flex-shrink-0">
   <div class="container">
      <div class="row">

         <!-- Search bar -->
         <div class="col-md-3 mt-5 mb-4">
            <div class="card card-body">
               <form method="get" novalidate>
                  <h3>{% trans 'filters' %}</h3>
                  <div class="form-group">
                     {{ form|crispy }}
                     <button class="btn btn-primary btn-block" type="submit">
                         <i class="fas fa-search"></i>
                         {% trans 'search_btn' %}
                     </button>
                  </div>
               </form>
            </div>
         </div>
         <!-- END Search bar -->

         <div class="col">
            <h1 class="h3 mb-3 font-weight-normal">
               {% trans 'posts' %}
            </h1>
            <!-- Posts -->
            {% for post in page_obj %}
            <div class="card mb-2 mt-2">
             <div class="card-header d-flex justify-content-between align-items-center">
                 <a class="d-flex align-items-center" href="{% url 'accounts:info' post.user.id %}">
                     <img class="avatar-mini mr-2" src="{% get_media_prefix %}{{ post.user.profile.avatar }}" />
                     <span class="text-muted">{{ post.user.username }}</span>
                 </a>
                 <span class="text-muted">{{ post.pub_date }}</span>
              </div>
               <div class="card-body text-dark">
                  <a href="{% url 'posts:single_post' post.id %}">
                      <h3 class="card-title">{{ post.name }}</h3>
                  </a>
                   <div class="d-flex justify-content-end">
                       <a href="{% url 'posts:single_post' post.id %}" class="btn btn-primary">
                           {% trans 'read_more' %}
                       </a>
                   </div>
               </div>
            </div>
            {% empty %}
                <h3 class="text-muted">{% trans 'empty_post_text' %}</h3>
            {% endfor %}
            <!-- END posts -->

            <!-- Pagination -->
             {% include '../utils/pagination.html' %}
            <!-- END Pagination -->

         </div>
      </div>
   </div>
</main>
{% endblock %}

templates/pages/profile.html
{% extends "../base.html" %}

{% load crispy_forms_tags static compress %}

{% block title %}Profile{% endblock %}

{% block content %}
 <main role="main" class="flex-shrink-0">
    <div class="container">

         <form method="post" enctype="multipart/form-data" novalidate>
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ next }}">
             <div class="container bootstrap snippet">
                 <h1 class="h3 mb-3 font-weight-normal">Profile</h1>
              <div class="row">
                    <div class="col-sm-3">
                      <div class="text-center">
                        <img src="{% get_media_prefix %}{{ user.profile.avatar }}" class="avatar img-circle img-thumbnail" alt="avatar">
                        {{ profile_form.avatar|as_crispy_field }}
                      </div>
                    </div>
                    <div class="col-sm-9">
                        <div class="form-row">
                          <div class="col-sm-6">
                                {{ user_form.last_name|as_crispy_field }}
                                {{ profile_form.birth_date|as_crispy_field }}
                          </div>
                            <div class="col-sm-6">
                                {{ user_form.first_name|as_crispy_field }}
                                {{ user_form.username|as_crispy_field }}
                          </div>
                        </div>
                        <div class="form-row">
                                {{ profile_form.about|as_crispy_field }}
                        </div>
                        <div>
                            <button class="btn btn-lg btn-primary" type="submit">Save</button>
                        </div>
                    </div>
                 </div>
              </div>
             </div>
        </form>
    </div>
 </main>
{% endblock %}
{% block js %}

        <script src="{% static 'js/jquery-3.5.0.min.js' %}"></script>
        <script src="{% static 'js/jquery.mask.min.js' %}"></script>
        <script src="{% static 'js/profile-page.js' %}"></script>
{% endblock %}

templates/pages/single_post.html
{% extends "../base.html" %}
{% block title %}My amazing blog{% endblock %}
{% block content %}
{% load i18n comment_tags %}
{% trans "La Grande Boucle" as race %}
 <main role="main" class="flex-shrink-0">
    <div class="container">

        <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">{% trans 'post_delete_modal_title' %}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {% trans 'post_delete_modal_body' %}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">
                {% trans 'cancel_btn' %}
            </button>
            <a href="{% url 'posts:delete_post' post.id %}" class="btn btn-danger">{% trans 'delete_btn' %}</a>
          </div>
        </div>
      </div>
    </div>

        <!-- Title -->
    <div class="d-flex justify-content-between align-items-end">
       <span class="h1 mt-4">{{ post.name }}</span>
        {% if user.is_authenticated and post.user.id == user.id %}
        <div>
            <a href="{% url 'posts:edit_post' post.id %}" class="btn btn-primary">{% trans 'edit_btn' %}</a>
            <button href="{% url 'posts:delete_post' post.id %}" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                {% trans 'delete_btn' %}
            </button>
        </div>
        {% endif %}
    </div>

    <!-- Author -->
    <p class="lead">
      by
      <a href="{% url 'accounts:info' post.user.id %}">{{ post.user.username }}</a>
    </p>

    <hr>

    <!-- Date/Time -->
    <p>Posted on {{ post.pub_date }}</p>

    <hr>

    <!-- Post Content -->
    {{ post.post|safe }}
    {% include_static_jquery %}
    {% render_comments post request %}
  </div>
 </main>
{% endblock %}

templates/pages/user_posts.html
{% extends "../base.html" %}
{% block title %}My amazing blog{% endblock %}
{% load crispy_forms_tags i18n %}
{% block content %}
<main role="main" class="flex-shrink-0">
   <div class="container">
      <div class="row">
         <div class="col">
            <h1 class="h3 mb-3 font-weight-normal">
               {% trans 'user_all_posts' %}
            </h1>
            <!-- Posts -->
            {% for post in page_obj %}

                <!-- Modal -->
            <div class="modal fade" id="delete-modal-{{ post.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">{% trans 'post_delete_modal_title' %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    {% trans 'post_delete_modal_body' %}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                        {% trans 'cancel_btn' %}
                    </button>
                    <a href="{% url 'posts:delete_post' post.id %}" class="btn btn-danger">{% trans 'delete_btn' %}</a>
                  </div>
                </div>
              </div>
            </div>

            <div class="card border-dark mb-2 mt-2">
               <div class="card-body text-dark">
                    <a href="{% url 'posts:single_post' post.id %}">
                        <h3 class="card-title">
                            {{ post.name }}
                            {% if post.is_published %}
                                <span class="badge badge-info ml-4">
                                    {% trans 'published' %}
                                </span>
                            {% endif %}
                        </h3>
                    </a>
                   <div class="d-flex justify-content-end">
                       <a href="{% url 'posts:single_post' post.id %}" class="btn btn-primary">{% trans 'read_more' %}</a>
                        <a href="{% url 'posts:edit_post' post.id %}" class="btn btn-primary">{% trans 'edit_btn' %}</a>
                        <button href="{% url 'posts:delete_post' post.id %}" class="btn btn-danger" data-toggle="modal" data-target="#delete-modal-{{ post.id }}">
                            {% trans 'delete_btn' %}
                        </button>
                   </div>
               </div>
            </div>
            {% endfor %}
            <!-- END posts -->

            <!-- Pagination -->
            {% include '../utils/pagination.html' %}
            <!-- END Pagination -->

         </div>
      </div>
   </div>
</main>
{% endblock %}

templates/pages/users.html
{% extends "../base.html" %}
{% load i18n static crispy_forms_tags %}
{% block title %}{% trans 'users' %}{% endblock %}
{% block content %}
 <main role="main" class="flex-shrink-0">
    <div class="container">
      <div class="row">

         <!-- Search bar -->
         <div class="col-md-3 mt-5 mb-4">
            <div class="card card-body">
               <form method="get" novalidate>
                   <h3>{% trans 'filters' %}</h3>
                  <div class="form-group">
                     {{ form|crispy }}
                     <button class="btn btn-primary btn-block" type="submit">
                         <i class="fas fa-search"></i>
                         {% trans 'search_btn' %}
                     </button>
                  </div>
               </form>
            </div>
         </div>
         <!-- END Search bar -->

         <div class="col">
            <h1 class="h3 mb-3 font-weight-normal">
               {% trans 'users' %}
            </h1>
            <div class="row mb-5">
            {% for user in page_obj %}
                <div class="col-md-4 col-lg-4 col-sm-6">
                    <div class="card mr-1 mb-4">
                        <a href="{% url 'accounts:info' user.id %}">
                            <img class="card-img-top" src="{% get_media_prefix %}{{ user.profile.avatar }}" alt="Card image cap">
                        </a>
                        <div class="card-body">
                            <a href="{% url 'accounts:info' user.id %}">
                                <h5 class="card-title">{{ user.username }}</h5>
                            </a>
                            <p class="card-text">
                                {% trans 'first_name' %}: {{ user.first_name }}
                            </p>
                            <p class="card-text">
                                {% trans 'last_name' %}: {{ user.last_name }}
                            </p>
                        </div>
                    </div>
                </div>
            {% empty %}
                <h3 class="text-muted">{% trans 'empty_user_text' %}</h3>
            {% endfor %}
            {% include '../utils/pagination.html' %}
            </div>
         </div>
      </div>
    </div>
 </main>
{% endblock %}