accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url('signup/', views.signup, name='registration'),
    url(r'^activate/(?P<uid64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/info/<int:id>', views.ProfileInfoView.as_view(), name='info'),
    url('users/', views.UsersView.as_view(), name='users'),
]

meow_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', IndexView.as_view(), name='index'),
    path('summernote/', include('django_summernote.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('comment/', include('comment.urls')),
    path('api/', include('comment.api.urls')),
    path('', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostsView.as_view(), name='all'),
    path('single/<int:id>', views.single_post, name='single_post'),
    path('create', views.create_post, name='create_post'),
    path('edit/<int:id>', views.EditPostView.as_view(), name='edit_post'),
    path('delete/<int:id>', views.DeletePostView.as_view(), name='delete_post'),
    path('user', views.UserPostsView.as_view(), name='user_posts'),
]

templates/base.html
{% load compress static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    {% compress css %}
        <link type="text/x-scss" href="{% static 'styles/main.scss' %}" rel="stylesheet" media="screen">
    {% endcompress %}

    {% block header %}{% endblock %}
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    <title>{% block title %}My amazing site{% endblock %}</title>
  </head>
  <body>

    {% include 'messages.html' %}
    {% include 'navbar.html' %}
    {% block content %}{% endblock %}
    {% block footer %}
        {% include 'footer.html' %}
    {% endblock %}

    <script src="{% static 'js/jquery-3.5.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% compress js %}
        <script src="{% static 'js/alerts-timeout-close.js' %}"></script>
    {% endcompress %}
    {% block js %}{% endblock %}
  </body>
</html>

templates/footer.html
<footer class="footer">
  <div class="container">
    <span class="text-muted">
        &copy; meow corporation
    </span>
  </div>
</footer>

templates/messages.html
{% if messages %}
<div class="alerts-container">
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible text-center alert-close-timeout" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    {{ message }}
    </div>
    {% endfor %}
    </div>
{% endif %}

templates/navbar.html
{% load i18n static %}
{% with url_name=request.resolver_match.view_name %}
<nav class="navbar navbar-expand-md fixed-top navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Left side collapse links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-nav mr-auto">
            <a class="nav-link {% if url_name == 'index' %}active{% endif %}" href="{% url 'index' %}">
                <i class="fas fa-home"></i>
                {% trans 'home' %}
            </a>
            <a class="nav-item nav-link {% if url_name == 'posts:all' %}active{% endif %}" href="{% url 'posts:all' %}">
                <i class="fas fa-copy"></i>
                {% trans 'posts' %}
            </a>
            <a class="nav-item nav-link {% if url_name == 'accounts:users' %}active{% endif %}" href="{% url 'accounts:users' %}">
                <i class="fas fa-users"></i>
                {% trans 'users' %}
            </a>
            {% if user.is_authenticated %}
            <a class="btn {% if url_name == 'posts:create_post' %}btn-primary{% else %}btn-outline-primary{% endif %} ml-md-4 d-flex align-items-center" href="{% url 'posts:create_post' %}">
                <i class="fas fa-edit"></i>
                {% trans 'crete_post' %}
            </a>
            {% endif %}
        </div>
        <!-- END Left side collapse links -->
        <!-- Right side collapse links -->
        <div>
            <ul class="navbar-nav">
                <!-- Select lang -->
                {% get_available_languages as languages %}
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                <li class="navbar-nav dropdown">
                        <a href="#" class="nav-link dropdown-toggle"  type="button" id="lang-switch-dropdown" data-toggle="dropdown" aria-haspopup="false" aria-expanded="false">
                        {% trans 'lang_label' %}:&nbsp;{{ LANGUAGE_CODE }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="lang-switch-dropdown">
                        {% for language in languages %}
                        <form action="{% url 'set_language' %}" method="post">
                            {% csrf_token %}
                            <input name="language" type="hidden" value="{{ language.code }}" />
                            <button class="dropdown-item {% if language.code == LANGUAGE_CODE %}active{% endif %}" type="submit">{{ language.name_local }}</button>
                        </form>
                        {% endfor %}
                    </div>
                </li>
                <!-- END Select lang -->
                {% if user.is_authenticated %}
                <li class="navbar-nav dropdown">
                    <a href="#" class="nav-link dropdown-toggle" type="button" id="user-dropdown" data-toggle="dropdown" aria-haspopup="false" aria-expanded="false">
                    {% trans 'user_label' %}:&nbsp;{{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="user-dropdown">
                        <a class="dropdown-item {% if url_name == 'accounts:profile' %}active{% endif %}" href="{% url 'accounts:profile' %}">
                            <i class="fas fa-user"></i>
                        {% trans 'profile' %}
                        </a>
                        <a class="dropdown-item {% if url_name == 'posts:user_posts' %}active{% endif %}" href="{% url 'posts:user_posts' %}">
                            <i class="fas fa-database"></i>
                            {% trans 'user_all_posts' %}
                        </a>
                        <a class="dropdown-item" href="{% url 'logout' %}">
                            <i class="fas fa-sign-out-alt"></i>
                            {% trans 'sign_out' %}
                        </a>
                    </div>
                </li>
            </ul>
            {% else %}
            <a href="{% url 'login' %}" type="button" class="btn btn-outline-primary mb-2 mb-md-0 d-flex align-items-center">
                {% trans 'sign_in' %}
            </a>
            <a href="{% url 'accounts:registration' %}" type="button" class="btn btn-outline-primary ml-md-2 d-flex align-items-center">
                {% trans 'sign_up' %}
            </a>
            {% endif %}
        </div>
        <!-- END Right side collapse links -->
    </div>
</nav>
{% endwith %}

templates/sidebar.html
{% load i18n %}
<nav id="sidebar" class="active">
    <div class="sidebar-header">
        <h3>Mica Mic Blog</h3>
        <strong>MB</strong>
    </div>

     {% with request.resolver_match.url_name as url_name %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if url_name == 'index' %}active{% endif %}">
        <a class="nav-link" href="{% url 'index' %}">
            <i class="fas fa-home"></i>
            {% trans 'nav_home' %}
            <span class="sr-only">(current)</span></a>
      </li>
    {% if user.is_authenticated %}
      <li class="nav-item {% if url_name == 'profile' %}active{% endif %}">
        <a class="nav-link" href="{% url 'accounts:profile' %}">
            <i class="fas fa-user"></i>
            {% trans 'nav_profile' %}
        </a>
      </li>
        <li class="nav-link{% if url_name == 'create_post' %}active{% endif %}">
            <a href="{% url 'posts:create_post' %}">
                <i class="fas fa-edit"></i>
                {% trans 'nav_crete_post' %}
            </a>
        </li>
        <li class="nav-link{% if url_name == 'user_posts' %}active{% endif %}">
            <a href="{% url 'posts:user_posts' %}">
                <i class="fas fa-database"></i>
                {% trans 'nav_user_all_posts' %}
            </a>
        </li>
    {% endif %}
        <li class="nav-link{% if url_name == 'create_post' %}active{% endif %}">
            <a href="{% url 'posts:create_post' %}">
                <i class="fas fa-users"></i>
                {% trans 'nav_users' %}
            </a>
        </li>
    </ul>
    {% endwith %}

<div>
       {% get_available_languages as languages %}
    {% get_current_language as LANGUAGE_CODE %}
    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as languages %}
    <div class="dropdown">
        <form action="{% url 'set_language' %}" method="post">
            {% csrf_token %}
          <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ LANGUAGE_CODE }}
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
              {% for language in languages %}
              <form action="{% url 'set_language' %}" method="post">
                  {% csrf_token %}
                  <input name="language" type="hidden" value="{{ language.code }}" />
                  <button class="dropdown-item" type="submit">{{ language.name_local }}</button>
              </form>
              {% endfor %}
          </div>
        </form>
    </div>

      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" type="button" class="btn btn-danger">Sign out</a>
      {% else %}
          <a href="{% url 'login' %}" type="button" class="btn btn-primary">Sign in</a>
          <a href="{% url 'accounts:registration' %}" type="button" class="btn btn-primary">Sign up</a>
      {% endif %}
    </div>

</nav>